# Book settings
title: Encryption Basics
author: Your Name
logo: logo.png
copyright: "2025"
exclude_patterns: [README.md]

# Execution settings
execute:
  execute_notebooks: auto
  timeout: 30

# HTML settings
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: favicon.ico
  google_analytics_id: ""  # Add your ID if needed
  home_page_in_navbar: true
  baseurl: "/encryption-basics-book"  # The base URL where your book will be hosted (GitHub Pages repository name)

# Launch button settings
launch_buttons:
  notebook_interface: "classic"  # or "jupyterlab"
  binderhub_url: ""  # Add your BinderHub URL if you want to enable Binder
  colab_url: "https://colab.research.google.com"

# Information about where the book exists on the web
repository:
  url: https://github.com/yourusername/encryption-basics-book  # Your GitHub repository URL
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links

# Add GitHub buttons to your book
html:
  use_repository_button: true

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
